
FROM golang:alpine AS builder
WORKDIR /app
COPY . .
RUN go build -o app


FROM alpine:latest
WORKDIR /app
RUN apk --no-cache add ca-certificates


COPY --from=builder /app/app .


COPY templates ./templates
COPY images ./images
COPY ascii-go ./ascii-go


COPY standard.txt .
COPY shadow.txt .
COPY thinkertoy.txt .

EXPOSE 3112
ENTRYPOINT ["./app"]
